# Auto-generated from the approved JP Planner personnel workbook.
PERSONNEL_SKILLS = ['Ik hou van Holland',
 'De Alleskunner',
 'Minute to Win It',
 'Moordspel',
 'Crazy Bingo',
 'Boogschieten',
 'Pubquiz',
 'Alles mag vandaag',
 'Hunted',
 'Expeditie Robinson',
 'Archery Tag',
 'Bubbelvoetbal',
 'Western Games',
 'Casino avond',
 'Action Painting',
 'VR Game La Casa de Papel',
 'Wie is de Mol',
 'Highland Games']

AVAILABILITY_SLOTS = ['Ma -17',
 'Ma >17',
 'Di -17',
 'Di >17',
 'Wo -17',
 'Wo >17',
 'Do -17',
 'Do >17',
 'Vr -17',
 'Vr >17',
 'Za -17',
 'Za >17',
 'Zo -17',
 'Zo >17']

PERSONNEL_SEED = [{'name': 'Jorian',
  'week_mode': '',
  'notes': 'Ma/zo alleen als het niet anders kan',
  'driving_license': 'Ja',
  'own_transport': 'Ja',
  'active': True,
  'availability': {'Ma -17': 'overleg',
                   'Ma >17': 'overleg',
                   'Di -17': 'beschikbaar',
                   'Di >17': 'beschikbaar',
                   'Wo -17': 'beschikbaar',
                   'Wo >17': 'beschikbaar',
                   'Do -17': 'beschikbaar',
                   'Do >17': 'beschikbaar',
                   'Vr -17': 'beschikbaar',
                   'Vr >17': 'beschikbaar',
                   'Za -17': 'beschikbaar',
                   'Za >17': 'beschikbaar',
                   'Zo -17': 'overleg',
                   'Zo >17': 'overleg'},
  'skills': {'Ik hou van Holland': 'Ja',
             'De Alleskunner': 'Ja',
             'Minute to Win It': 'Ja',
             'Moordspel': 'Ja',
             'Crazy Bingo': 'Ja',
             'Boogschieten': 'Ja',
             'Pubquiz': 'Ja',
             'Alles mag vandaag': 'Ja',
             'Hunted': 'Ja',
             'Expeditie Robinson': 'Ja',
             'Archery Tag': 'Ja',
             'Bubbelvoetbal': 'Ja',
             'Western Games': 'Ja',
             'Casino avond': 'Ja',
             'Action Painting': 'Onbekend',
             'VR Game La Casa de Papel': 'Ja',
             'Wie is de Mol': 'Ja',
             'Highland Games': 'Ja'}},
 {'name': 'Willeke',
  'week_mode': '',
  'notes': 'Ma/zo alleen als het niet anders kan',
  'driving_license': 'Ja',
  'own_transport': 'Ja',
  'active': True,
  'availability': {'Ma -17': 'overleg',
                   'Ma >17': 'overleg',
                   'Di -17': 'beschikbaar',
                   'Di >17': 'beschikbaar',
                   'Wo -17': 'beschikbaar',
                   'Wo >17': 'beschikbaar',
                   'Do -17': 'beschikbaar',
                   'Do >17': 'beschikbaar',
                   'Vr -17': 'beschikbaar',
                   'Vr >17': 'beschikbaar',
                   'Za -17': 'beschikbaar',
                   'Za >17': 'beschikbaar',
                   'Zo -17': 'overleg',
                   'Zo >17': 'overleg'},
  'skills': {'Ik hou van Holland': 'Ja',
             'De Alleskunner': 'Ja',
             'Minute to Win It': 'Ja',
             'Moordspel': 'Ja',
             'Crazy Bingo': 'Ja',
             'Boogschieten': 'Ja',
             'Pubquiz': 'Ja',
             'Alles mag vandaag': 'Ja',
             'Hunted': 'Ja',
             'Expeditie Robinson': 'Ja',
             'Archery Tag': 'Ja',
             'Bubbelvoetbal': 'Ja',
             'Western Games': 'Ja',
             'Casino avond': 'Ja',
             'Action Painting': 'Onbekend',
             'VR Game La Casa de Papel': 'Ja',
             'Wie is de Mol': 'Ja',
             'Highland Games': 'Ja'}},
 {'name': 'Dennis',
  'week_mode': '',
  'notes': 'Zaterdag om de week',
  'driving_license': 'Ja',
  'own_transport': 'Ja',
  'active': True,
  'availability': {'Ma -17': 'niet',
                   'Ma >17': 'niet',
                   'Di -17': 'beschikbaar',
                   'Di >17': 'beschikbaar',
                   'Wo -17': 'niet',
                   'Wo >17': 'niet',
                   'Do -17': 'beschikbaar',
                   'Do >17': 'beschikbaar',
                   'Vr -17': 'niet',
                   'Vr >17': 'niet',
                   'Za -17': 'overleg',
                   'Za >17': 'overleg',
                   'Zo -17': 'niet',
                   'Zo >17': 'niet'},
  'skills': {'Ik hou van Holland': 'Ja',
             'De Alleskunner': 'Ja',
             'Minute to Win It': 'Ja',
             'Moordspel': 'Ja',
             'Crazy Bingo': 'Ja',
             'Boogschieten': 'Ja',
             'Pubquiz': 'Ja',
             'Alles mag vandaag': 'Ja',
             'Hunted': 'Ja',
             'Expeditie Robinson': 'Ja',
             'Archery Tag': 'Ja',
             'Bubbelvoetbal': 'Ja',
             'Western Games': 'Ja',
             'Casino avond': 'Ja',
             'Action Painting': 'Onbekend',
             'VR Game La Casa de Papel': 'Ja',
             'Wie is de Mol': 'Ja',
             'Highland Games': 'Ja'}},
 {'name': 'Michiel',
  'week_mode': '',
  'notes': 'Vaker beschikbaar; donderdag sowieso niet',
  'driving_license': 'Ja',
  'own_transport': 'Onbekend',
  'active': True,
  'availability': {'Ma -17': 'onbekend',
                   'Ma >17': 'onbekend',
                   'Di -17': 'onbekend',
                   'Di >17': 'onbekend',
                   'Wo -17': 'onbekend',
                   'Wo >17': 'onbekend',
                   'Do -17': 'niet',
                   'Do >17': 'niet',
                   'Vr -17': 'onbekend',
                   'Vr >17': 'onbekend',
                   'Za -17': 'beschikbaar',
                   'Za >17': 'beschikbaar',
                   'Zo -17': 'onbekend',
                   'Zo >17': 'onbekend'},
  'skills': {'Ik hou van Holland': 'Ja',
             'De Alleskunner': 'Ja',
             'Minute to Win It': 'Ja',
             'Moordspel': 'Ja',
             'Crazy Bingo': 'Ja',
             'Boogschieten': 'Ja',
             'Pubquiz': 'Ja',
             'Alles mag vandaag': 'Ja',
             'Hunted': 'Ja',
             'Expeditie Robinson': 'Ja',
             'Archery Tag': 'Ja',
             'Bubbelvoetbal': 'Ja',
             'Western Games': 'Ja',
             'Casino avond': 'Ja',
             'Action Painting': 'Onbekend',
             'VR Game La Casa de Papel': 'Ja',
             'Wie is de Mol': 'Ja',
             'Highland Games': 'Ja'}},
 {'name': 'Claire',
  'week_mode': '',
  'notes': 'Vaste beschikbaarheid zondag',
  'driving_license': 'Ja',
  'own_transport': 'Onbekend',
  'active': True,
  'availability': {'Ma -17': 'niet',
                   'Ma >17': 'niet',
                   'Di -17': 'niet',
                   'Di >17': 'niet',
                   'Wo -17': 'niet',
                   'Wo >17': 'niet',
                   'Do -17': 'niet',
                   'Do >17': 'niet',
                   'Vr -17': 'niet',
                   'Vr >17': 'niet',
                   'Za -17': 'niet',
                   'Za >17': 'niet',
                   'Zo -17': 'beschikbaar',
                   'Zo >17': 'beschikbaar'},
  'skills': {'Ik hou van Holland': 'Ja',
             'De Alleskunner': 'Ja',
             'Minute to Win It': 'Ja',
             'Moordspel': 'Ja',
             'Crazy Bingo': 'Ja',
             'Boogschieten': 'Onbekend',
             'Pubquiz': 'Ja',
             'Alles mag vandaag': 'Onbekend',
             'Hunted': 'Onbekend',
             'Expeditie Robinson': 'Onbekend',
             'Archery Tag': 'Ja',
             'Bubbelvoetbal': 'Ja',
             'Western Games': 'Onbekend',
             'Casino avond': 'Ja',
             'Action Painting': 'Onbekend',
             'VR Game La Casa de Papel': 'Onbekend',
             'Wie is de Mol': 'Onbekend',
             'Highland Games': 'Onbekend'}},
 {'name': 'Natascha',
  'week_mode': '',
  'notes': 'Om het weekend het hele weekend',
  'driving_license': 'Ja',
  'own_transport': 'Ja',
  'active': True,
  'availability': {'Ma -17': 'beschikbaar',
                   'Ma >17': 'beschikbaar',
                   'Di -17': 'beschikbaar',
                   'Di >17': 'beschikbaar',
                   'Wo -17': 'niet',
                   'Wo >17': 'niet',
                   'Do -17': 'beschikbaar',
                   'Do >17': 'beschikbaar',
                   'Vr -17': 'beschikbaar',
                   'Vr >17': 'beschikbaar',
                   'Za -17': 'overleg',
                   'Za >17': 'overleg',
                   'Zo -17': 'overleg',
                   'Zo >17': 'overleg'},
  'skills': {'Ik hou van Holland': 'Ja',
             'De Alleskunner': 'Ja',
             'Minute to Win It': 'Ja',
             'Moordspel': 'Ja',
             'Crazy Bingo': 'Ja',
             'Boogschieten': 'Ja',
             'Pubquiz': 'Ja',
             'Alles mag vandaag': 'Ja',
             'Hunted': 'Ja',
             'Expeditie Robinson': 'Ja',
             'Archery Tag': 'Ja',
             'Bubbelvoetbal': 'Ja',
             'Western Games': 'Ja',
             'Casino avond': 'Ja',
             'Action Painting': 'Onbekend',
             'VR Game La Casa de Papel': 'Ja',
             'Wie is de Mol': 'Ja',
             'Highland Games': 'Ja'}},
 {'name': 'Lisanne',
  'week_mode': '',
  'notes': 'Dinsdag t/m zaterdag',
  'driving_license': 'Ja',
  'own_transport': 'Ja',
  'active': True,
  'availability': {'Ma -17': 'niet',
                   'Ma >17': 'niet',
                   'Di -17': 'beschikbaar',
                   'Di >17': 'beschikbaar',
                   'Wo -17': 'beschikbaar',
                   'Wo >17': 'beschikbaar',
                   'Do -17': 'beschikbaar',
                   'Do >17': 'beschikbaar',
                   'Vr -17': 'beschikbaar',
                   'Vr >17': 'beschikbaar',
                   'Za -17': 'beschikbaar',
                   'Za >17': 'beschikbaar',
                   'Zo -17': 'niet',
                   'Zo >17': 'niet'},
  'skills': {'Ik hou van Holland': 'Ja',
             'De Alleskunner': 'Ja',
             'Minute to Win It': 'Ja',
             'Moordspel': 'Ja',
             'Crazy Bingo': 'Ja',
             'Boogschieten': 'Ja',
             'Pubquiz': 'Ja',
             'Alles mag vandaag': 'Ja',
             'Hunted': 'Ja',
             'Expeditie Robinson': 'Ja',
             'Archery Tag': 'Ja',
             'Bubbelvoetbal': 'Ja',
             'Western Games': 'Ja',
             'Casino avond': 'Ja',
             'Action Painting': 'Onbekend',
             'VR Game La Casa de Papel': 'Ja',
             'Wie is de Mol': 'Ja',
             'Highland Games': 'Ja'}},
 {'name': 'Mira',
  'week_mode': '',
  'notes': 'Woensdag en vrijdag vast',
  'driving_license': 'Ja',
  'own_transport': 'Ja',
  'active': True,
  'availability': {'Ma -17': 'niet',
                   'Ma >17': 'niet',
                   'Di -17': 'niet',
                   'Di >17': 'niet',
                   'Wo -17': 'beschikbaar',
                   'Wo >17': 'beschikbaar',
                   'Do -17': 'niet',
                   'Do >17': 'niet',
                   'Vr -17': 'beschikbaar',
                   'Vr >17': 'beschikbaar',
                   'Za -17': 'niet',
                   'Za >17': 'niet',
                   'Zo -17': 'niet',
                   'Zo >17': 'niet'},
  'skills': {'Ik hou van Holland': 'Onbekend',
             'De Alleskunner': 'Onbekend',
             'Minute to Win It': 'Onbekend',
             'Moordspel': 'Onbekend',
             'Crazy Bingo': 'Onbekend',
             'Boogschieten': 'Onbekend',
             'Pubquiz': 'Onbekend',
             'Alles mag vandaag': 'Onbekend',
             'Hunted': 'Onbekend',
             'Expeditie Robinson': 'Onbekend',
             'Archery Tag': 'Onbekend',
             'Bubbelvoetbal': 'Onbekend',
             'Western Games': 'Onbekend',
             'Casino avond': 'Onbekend',
             'Action Painting': 'Onbekend',
             'VR Game La Casa de Papel': 'Onbekend',
             'Wie is de Mol': 'Onbekend',
             'Highland Games': 'Onbekend'}},
 {'name': 'Jacobien',
  'week_mode': '',
  'notes': 'Do/za afgesproken, maar niet altijd',
  'driving_license': 'Ja',
  'own_transport': 'Onbekend',
  'active': True,
  'availability': {'Ma -17': 'niet',
                   'Ma >17': 'niet',
                   'Di -17': 'niet',
                   'Di >17': 'niet',
                   'Wo -17': 'niet',
                   'Wo >17': 'niet',
                   'Do -17': 'overleg',
                   'Do >17': 'overleg',
                   'Vr -17': 'niet',
                   'Vr >17': 'niet',
                   'Za -17': 'overleg',
                   'Za >17': 'overleg',
                   'Zo -17': 'niet',
                   'Zo >17': 'niet'},
  'skills': {'Ik hou van Holland': 'Ja',
             'De Alleskunner': 'Ja',
             'Minute to Win It': 'Ja',
             'Moordspel': 'Ja',
             'Crazy Bingo': 'Ja',
             'Boogschieten': 'Ja',
             'Pubquiz': 'Ja',
             'Alles mag vandaag': 'Ja',
             'Hunted': 'Ja',
             'Expeditie Robinson': 'Ja',
             'Archery Tag': 'Ja',
             'Bubbelvoetbal': 'Ja',
             'Western Games': 'Ja',
             'Casino avond': 'Ja',
             'Action Painting': 'Onbekend',
             'VR Game La Casa de Papel': 'Ja',
             'Wie is de Mol': 'Ja',
             'Highland Games': 'Ja'}},
 {'name': 'Tim Wijst',
  'week_mode': '',
  'notes': 'Donderdag, vaak niet hele dag',
  'driving_license': 'Ja',
  'own_transport': 'Ja',
  'active': True,
  'availability': {'Ma -17': 'niet',
                   'Ma >17': 'niet',
                   'Di -17': 'niet',
                   'Di >17': 'niet',
                   'Wo -17': 'niet',
                   'Wo >17': 'niet',
                   'Do -17': 'overleg',
                   'Do >17': 'overleg',
                   'Vr -17': 'niet',
                   'Vr >17': 'niet',
                   'Za -17': 'niet',
                   'Za >17': 'niet',
                   'Zo -17': 'niet',
                   'Zo >17': 'niet'},
  'skills': {'Ik hou van Holland': 'Ja',
             'De Alleskunner': 'Ja',
             'Minute to Win It': 'Ja',
             'Moordspel': 'Ja',
             'Crazy Bingo': 'Ja',
             'Boogschieten': 'Onbekend',
             'Pubquiz': 'Ja',
             'Alles mag vandaag': 'Onbekend',
             'Hunted': 'Onbekend',
             'Expeditie Robinson': 'Onbekend',
             'Archery Tag': 'Onbekend',
             'Bubbelvoetbal': 'Onbekend',
             'Western Games': 'Onbekend',
             'Casino avond': 'Onbekend',
             'Action Painting': 'Onbekend',
             'VR Game La Casa de Papel': 'Onbekend',
             'Wie is de Mol': 'Onbekend',
             'Highland Games': 'Onbekend'}},
 {'name': 'Jennifer',
  'week_mode': '',
  'notes': 'Zaterdag, vaak niet hele dag',
  'driving_license': 'Ja',
  'own_transport': 'Onbekend',
  'active': True,
  'availability': {'Ma -17': 'niet',
                   'Ma >17': 'niet',
                   'Di -17': 'niet',
                   'Di >17': 'niet',
                   'Wo -17': 'niet',
                   'Wo >17': 'niet',
                   'Do -17': 'niet',
                   'Do >17': 'niet',
                   'Vr -17': 'niet',
                   'Vr >17': 'niet',
                   'Za -17': 'overleg',
                   'Za >17': 'overleg',
                   'Zo -17': 'niet',
                   'Zo >17': 'niet'},
  'skills': {'Ik hou van Holland': 'Ja',
             'De Alleskunner': 'Ja',
             'Minute to Win It': 'Ja',
             'Moordspel': 'Ja',
             'Crazy Bingo': 'Ja',
             'Boogschieten': 'Ja',
             'Pubquiz': 'Ja',
             'Alles mag vandaag': 'Ja',
             'Hunted': 'Ja',
             'Expeditie Robinson': 'Ja',
             'Archery Tag': 'Ja',
             'Bubbelvoetbal': 'Ja',
             'Western Games': 'Ja',
             'Casino avond': 'Ja',
             'Action Painting': 'Onbekend',
             'VR Game La Casa de Papel': 'Ja',
             'Wie is de Mol': 'Ja',
             'Highland Games': 'Ja'}},
 {'name': 'Jelle',
  'week_mode': '',
  'notes': 'Alleen in nood',
  'driving_license': 'Ja',
  'own_transport': 'Ja',
  'active': True,
  'availability': {'Ma -17': 'overleg',
                   'Ma >17': 'overleg',
                   'Di -17': 'overleg',
                   'Di >17': 'overleg',
                   'Wo -17': 'overleg',
                   'Wo >17': 'overleg',
                   'Do -17': 'overleg',
                   'Do >17': 'overleg',
                   'Vr -17': 'overleg',
                   'Vr >17': 'overleg',
                   'Za -17': 'overleg',
                   'Za >17': 'overleg',
                   'Zo -17': 'overleg',
                   'Zo >17': 'overleg'},
  'skills': {'Ik hou van Holland': 'Ja',
             'De Alleskunner': 'Ja',
             'Minute to Win It': 'Ja',
             'Moordspel': 'Ja',
             'Crazy Bingo': 'Ja',
             'Boogschieten': 'Ja',
             'Pubquiz': 'Ja',
             'Alles mag vandaag': 'Ja',
             'Hunted': 'Ja',
             'Expeditie Robinson': 'Ja',
             'Archery Tag': 'Ja',
             'Bubbelvoetbal': 'Ja',
             'Western Games': 'Ja',
             'Casino avond': 'Ja',
             'Action Painting': 'Onbekend',
             'VR Game La Casa de Papel': 'Ja',
             'Wie is de Mol': 'Ja',
             'Highland Games': 'Ja'}},
 {'name': 'Margriet Vries',
  'week_mode': '',
  'notes': 'Beschikbaarheid nog afspreken',
  'driving_license': 'Ja',
  'own_transport': 'Ja',
  'active': True,
  'availability': {'Ma -17': 'onbekend',
                   'Ma >17': 'onbekend',
                   'Di -17': 'onbekend',
                   'Di >17': 'onbekend',
                   'Wo -17': 'onbekend',
                   'Wo >17': 'onbekend',
                   'Do -17': 'onbekend',
                   'Do >17': 'onbekend',
                   'Vr -17': 'onbekend',
                   'Vr >17': 'onbekend',
                   'Za -17': 'onbekend',
                   'Za >17': 'onbekend',
                   'Zo -17': 'onbekend',
                   'Zo >17': 'onbekend'},
  'skills': {'Ik hou van Holland': 'Ja',
             'De Alleskunner': 'Ja',
             'Minute to Win It': 'Ja',
             'Moordspel': 'Ja',
             'Crazy Bingo': 'Ja',
             'Boogschieten': 'Onbekend',
             'Pubquiz': 'Ja',
             'Alles mag vandaag': 'Onbekend',
             'Hunted': 'Onbekend',
             'Expeditie Robinson': 'Onbekend',
             'Archery Tag': 'Onbekend',
             'Bubbelvoetbal': 'Onbekend',
             'Western Games': 'Onbekend',
             'Casino avond': 'Onbekend',
             'Action Painting': 'Onbekend',
             'VR Game La Casa de Papel': 'Onbekend',
             'Wie is de Mol': 'Onbekend',
             'Highland Games': 'Onbekend'}},
 {'name': 'Patrick S',
  'week_mode': '',
  'notes': 'Weekenden soms; vanuit Paviljoen',
  'driving_license': 'Ja',
  'own_transport': 'Onbekend',
  'active': True,
  'availability': {'Ma -17': 'niet',
                   'Ma >17': 'niet',
                   'Di -17': 'niet',
                   'Di >17': 'niet',
                   'Wo -17': 'niet',
                   'Wo >17': 'niet',
                   'Do -17': 'niet',
                   'Do >17': 'niet',
                   'Vr -17': 'niet',
                   'Vr >17': 'niet',
                   'Za -17': 'overleg',
                   'Za >17': 'overleg',
                   'Zo -17': 'overleg',
                   'Zo >17': 'overleg'},
  'skills': {'Ik hou van Holland': 'Ja',
             'De Alleskunner': 'Ja',
             'Minute to Win It': 'Ja',
             'Moordspel': 'Ja',
             'Crazy Bingo': 'Ja',
             'Boogschieten': 'Onbekend',
             'Pubquiz': 'Onbekend',
             'Alles mag vandaag': 'Onbekend',
             'Hunted': 'Onbekend',
             'Expeditie Robinson': 'Onbekend',
             'Archery Tag': 'Onbekend',
             'Bubbelvoetbal': 'Onbekend',
             'Western Games': 'Onbekend',
             'Casino avond': 'Onbekend',
             'Action Painting': 'Onbekend',
             'VR Game La Casa de Papel': 'Onbekend',
             'Wie is de Mol': 'Onbekend',
             'Highland Games': 'Onbekend'}},
 {'name': 'Luna',
  'week_mode': '',
  'notes': 'Vr/za/zo rondom hockey; do avond training',
  'driving_license': 'Ja',
  'own_transport': 'Onbekend',
  'active': True,
  'availability': {'Ma -17': 'niet',
                   'Ma >17': 'niet',
                   'Di -17': 'niet',
                   'Di >17': 'niet',
                   'Wo -17': 'niet',
                   'Wo >17': 'niet',
                   'Do -17': 'niet',
                   'Do >17': 'niet',
                   'Vr -17': 'overleg',
                   'Vr >17': 'overleg',
                   'Za -17': 'overleg',
                   'Za >17': 'overleg',
                   'Zo -17': 'overleg',
                   'Zo >17': 'overleg'},
  'skills': {'Ik hou van Holland': 'Onbekend',
             'De Alleskunner': 'Onbekend',
             'Minute to Win It': 'Onbekend',
             'Moordspel': 'Ja',
             'Crazy Bingo': 'Onbekend',
             'Boogschieten': 'Onbekend',
             'Pubquiz': 'Onbekend',
             'Alles mag vandaag': 'Onbekend',
             'Hunted': 'Onbekend',
             'Expeditie Robinson': 'Onbekend',
             'Archery Tag': 'Onbekend',
             'Bubbelvoetbal': 'Onbekend',
             'Western Games': 'Onbekend',
             'Casino avond': 'Onbekend',
             'Action Painting': 'Onbekend',
             'VR Game La Casa de Papel': 'Onbekend',
             'Wie is de Mol': 'Onbekend',
             'Highland Games': 'Onbekend'}},
 {'name': 'Meike',
  'week_mode': '',
  'notes': 'Vrijdag en zaterdag',
  'driving_license': 'Ja',
  'own_transport': 'Onbekend',
  'active': True,
  'availability': {'Ma -17': 'niet',
                   'Ma >17': 'niet',
                   'Di -17': 'niet',
                   'Di >17': 'niet',
                   'Wo -17': 'niet',
                   'Wo >17': 'niet',
                   'Do -17': 'niet',
                   'Do >17': 'niet',
                   'Vr -17': 'beschikbaar',
                   'Vr >17': 'beschikbaar',
                   'Za -17': 'beschikbaar',
                   'Za >17': 'beschikbaar',
                   'Zo -17': 'niet',
                   'Zo >17': 'niet'},
  'skills': {'Ik hou van Holland': 'Onbekend',
             'De Alleskunner': 'Onbekend',
             'Minute to Win It': 'Onbekend',
             'Moordspel': 'Ja',
             'Crazy Bingo': 'Onbekend',
             'Boogschieten': 'Onbekend',
             'Pubquiz': 'Onbekend',
             'Alles mag vandaag': 'Onbekend',
             'Hunted': 'Onbekend',
             'Expeditie Robinson': 'Onbekend',
             'Archery Tag': 'Onbekend',
             'Bubbelvoetbal': 'Onbekend',
             'Western Games': 'Onbekend',
             'Casino avond': 'Onbekend',
             'Action Painting': 'Onbekend',
             'VR Game La Casa de Papel': 'Onbekend',
             'Wie is de Mol': 'Onbekend',
             'Highland Games': 'Onbekend'}},
 {'name': 'Cerchio',
  'week_mode': '',
  'notes': 'Donderdag beschikbaar tot 20:00',
  'driving_license': 'Ja',
  'own_transport': 'Onbekend',
  'active': True,
  'availability': {'Ma -17': 'niet',
                   'Ma >17': 'niet',
                   'Di -17': 'niet',
                   'Di >17': 'niet',
                   'Wo -17': 'niet',
                   'Wo >17': 'niet',
                   'Do -17': 'beschikbaar',
                   'Do >17': 'overleg',
                   'Vr -17': 'beschikbaar',
                   'Vr >17': 'beschikbaar',
                   'Za -17': 'niet',
                   'Za >17': 'niet',
                   'Zo -17': 'beschikbaar',
                   'Zo >17': 'beschikbaar'},
  'skills': {'Ik hou van Holland': 'Onbekend',
             'De Alleskunner': 'Onbekend',
             'Minute to Win It': 'Onbekend',
             'Moordspel': 'Ja',
             'Crazy Bingo': 'Onbekend',
             'Boogschieten': 'Onbekend',
             'Pubquiz': 'Onbekend',
             'Alles mag vandaag': 'Onbekend',
             'Hunted': 'Onbekend',
             'Expeditie Robinson': 'Onbekend',
             'Archery Tag': 'Onbekend',
             'Bubbelvoetbal': 'Onbekend',
             'Western Games': 'Onbekend',
             'Casino avond': 'Onbekend',
             'Action Painting': 'Onbekend',
             'VR Game La Casa de Papel': 'Onbekend',
             'Wie is de Mol': 'Onbekend',
             'Highland Games': 'Onbekend'}},
 {'name': 'Horatio',
  'week_mode': '',
  'notes': 'Vanaf 17-09-2026 wo t/m zo; SEM wijkt af',
  'driving_license': 'Ja',
  'own_transport': 'Onbekend',
  'active': True,
  'availability': {'Ma -17': 'niet',
                   'Ma >17': 'niet',
                   'Di -17': 'niet',
                   'Di >17': 'niet',
                   'Wo -17': 'overleg',
                   'Wo >17': 'overleg',
                   'Do -17': 'overleg',
                   'Do >17': 'overleg',
                   'Vr -17': 'overleg',
                   'Vr >17': 'overleg',
                   'Za -17': 'overleg',
                   'Za >17': 'overleg',
                   'Zo -17': 'overleg',
                   'Zo >17': 'overleg'},
  'skills': {'Ik hou van Holland': 'Onbekend',
             'De Alleskunner': 'Onbekend',
             'Minute to Win It': 'Onbekend',
             'Moordspel': 'Ja',
             'Crazy Bingo': 'Onbekend',
             'Boogschieten': 'Onbekend',
             'Pubquiz': 'Onbekend',
             'Alles mag vandaag': 'Onbekend',
             'Hunted': 'Onbekend',
             'Expeditie Robinson': 'Onbekend',
             'Archery Tag': 'Onbekend',
             'Bubbelvoetbal': 'Onbekend',
             'Western Games': 'Onbekend',
             'Casino avond': 'Onbekend',
             'Action Painting': 'Onbekend',
             'VR Game La Casa de Papel': 'Onbekend',
             'Wie is de Mol': 'Onbekend',
             'Highland Games': 'Onbekend'}},
 {'name': 'Bastian',
  'week_mode': '',
  'notes': 'Woensdag soms; ma/di/do nooit',
  'driving_license': 'Ja',
  'own_transport': 'Onbekend',
  'active': True,
  'availability': {'Ma -17': 'niet',
                   'Ma >17': 'niet',
                   'Di -17': 'niet',
                   'Di >17': 'niet',
                   'Wo -17': 'overleg',
                   'Wo >17': 'overleg',
                   'Do -17': 'niet',
                   'Do >17': 'niet',
                   'Vr -17': 'beschikbaar',
                   'Vr >17': 'beschikbaar',
                   'Za -17': 'beschikbaar',
                   'Za >17': 'beschikbaar',
                   'Zo -17': 'beschikbaar',
                   'Zo >17': 'beschikbaar'},
  'skills': {'Ik hou van Holland': 'Ja',
             'De Alleskunner': 'Ja',
             'Minute to Win It': 'Ja',
             'Moordspel': 'Ja',
             'Crazy Bingo': 'Ja',
             'Boogschieten': 'Ja',
             'Pubquiz': 'Ja',
             'Alles mag vandaag': 'Ja',
             'Hunted': 'Ja',
             'Expeditie Robinson': 'Ja',
             'Archery Tag': 'Ja',
             'Bubbelvoetbal': 'Ja',
             'Western Games': 'Ja',
             'Casino avond': 'Ja',
             'Action Painting': 'Onbekend',
             'VR Game La Casa de Papel': 'Ja',
             'Wie is de Mol': 'Ja',
             'Highland Games': 'Ja'}},
 {'name': 'Naomi',
  'week_mode': '',
  'notes': 'Nog geen dagen afgesproken; automaatrijbewijs',
  'driving_license': 'Ja',
  'own_transport': 'Onbekend',
  'active': True,
  'availability': {'Ma -17': 'onbekend',
                   'Ma >17': 'onbekend',
                   'Di -17': 'onbekend',
                   'Di >17': 'onbekend',
                   'Wo -17': 'onbekend',
                   'Wo >17': 'onbekend',
                   'Do -17': 'onbekend',
                   'Do >17': 'onbekend',
                   'Vr -17': 'onbekend',
                   'Vr >17': 'onbekend',
                   'Za -17': 'onbekend',
                   'Za >17': 'onbekend',
                   'Zo -17': 'onbekend',
                   'Zo >17': 'onbekend'},
  'skills': {'Ik hou van Holland': 'Onbekend',
             'De Alleskunner': 'Onbekend',
             'Minute to Win It': 'Onbekend',
             'Moordspel': 'Ja',
             'Crazy Bingo': 'Onbekend',
             'Boogschieten': 'Onbekend',
             'Pubquiz': 'Onbekend',
             'Alles mag vandaag': 'Onbekend',
             'Hunted': 'Onbekend',
             'Expeditie Robinson': 'Onbekend',
             'Archery Tag': 'Onbekend',
             'Bubbelvoetbal': 'Onbekend',
             'Western Games': 'Onbekend',
             'Casino avond': 'Onbekend',
             'Action Painting': 'Onbekend',
             'VR Game La Casa de Papel': 'Onbekend',
             'Wie is de Mol': 'Onbekend',
             'Highland Games': 'Onbekend'}},
 {'name': 'Ada',
  'week_mode': '',
  'notes': 'Vr/za/zo, maar soms toch niet beschikbaar',
  'driving_license': 'Ja',
  'own_transport': 'Onbekend',
  'active': True,
  'availability': {'Ma -17': 'niet',
                   'Ma >17': 'niet',
                   'Di -17': 'niet',
                   'Di >17': 'niet',
                   'Wo -17': 'niet',
                   'Wo >17': 'niet',
                   'Do -17': 'niet',
                   'Do >17': 'niet',
                   'Vr -17': 'overleg',
                   'Vr >17': 'overleg',
                   'Za -17': 'overleg',
                   'Za >17': 'overleg',
                   'Zo -17': 'overleg',
                   'Zo >17': 'overleg'},
  'skills': {'Ik hou van Holland': 'Onbekend',
             'De Alleskunner': 'Onbekend',
             'Minute to Win It': 'Onbekend',
             'Moordspel': 'Ja',
             'Crazy Bingo': 'Onbekend',
             'Boogschieten': 'Onbekend',
             'Pubquiz': 'Onbekend',
             'Alles mag vandaag': 'Onbekend',
             'Hunted': 'Onbekend',
             'Expeditie Robinson': 'Onbekend',
             'Archery Tag': 'Onbekend',
             'Bubbelvoetbal': 'Onbekend',
             'Western Games': 'Onbekend',
             'Casino avond': 'Onbekend',
             'Action Painting': 'Onbekend',
             'VR Game La Casa de Papel': 'Onbekend',
             'Wie is de Mol': 'Onbekend',
             'Highland Games': 'Onbekend'}},
 {'name': 'Ayla',
  'week_mode': '',
  'notes': 'Donderdag tot 19:00; zondag eventueel',
  'driving_license': 'Ja',
  'own_transport': 'Onbekend',
  'active': True,
  'availability': {'Ma -17': 'niet',
                   'Ma >17': 'niet',
                   'Di -17': 'niet',
                   'Di >17': 'niet',
                   'Wo -17': 'niet',
                   'Wo >17': 'niet',
                   'Do -17': 'beschikbaar',
                   'Do >17': 'overleg',
                   'Vr -17': 'beschikbaar',
                   'Vr >17': 'beschikbaar',
                   'Za -17': 'beschikbaar',
                   'Za >17': 'beschikbaar',
                   'Zo -17': 'overleg',
                   'Zo >17': 'overleg'},
  'skills': {'Ik hou van Holland': 'Onbekend',
             'De Alleskunner': 'Onbekend',
             'Minute to Win It': 'Onbekend',
             'Moordspel': 'Ja',
             'Crazy Bingo': 'Onbekend',
             'Boogschieten': 'Onbekend',
             'Pubquiz': 'Onbekend',
             'Alles mag vandaag': 'Onbekend',
             'Hunted': 'Onbekend',
             'Expeditie Robinson': 'Onbekend',
             'Archery Tag': 'Onbekend',
             'Bubbelvoetbal': 'Onbekend',
             'Western Games': 'Onbekend',
             'Casino avond': 'Onbekend',
             'Action Painting': 'Onbekend',
             'VR Game La Casa de Papel': 'Onbekend',
             'Wie is de Mol': 'Onbekend',
             'Highland Games': 'Onbekend'}},
 {'name': 'Aniek',
  'week_mode': '',
  'notes': 'Stagiaire; dinsdag t/m zaterdag',
  'driving_license': 'Ja',
  'own_transport': 'Onbekend',
  'active': True,
  'availability': {'Ma -17': 'niet',
                   'Ma >17': 'niet',
                   'Di -17': 'beschikbaar',
                   'Di >17': 'beschikbaar',
                   'Wo -17': 'beschikbaar',
                   'Wo >17': 'beschikbaar',
                   'Do -17': 'beschikbaar',
                   'Do >17': 'beschikbaar',
                   'Vr -17': 'beschikbaar',
                   'Vr >17': 'beschikbaar',
                   'Za -17': 'beschikbaar',
                   'Za >17': 'beschikbaar',
                   'Zo -17': 'niet',
                   'Zo >17': 'niet'},
  'skills': {'Ik hou van Holland': 'Onbekend',
             'De Alleskunner': 'Onbekend',
             'Minute to Win It': 'Onbekend',
             'Moordspel': 'Ja',
             'Crazy Bingo': 'Onbekend',
             'Boogschieten': 'Onbekend',
             'Pubquiz': 'Onbekend',
             'Alles mag vandaag': 'Onbekend',
             'Hunted': 'Onbekend',
             'Expeditie Robinson': 'Onbekend',
             'Archery Tag': 'Onbekend',
             'Bubbelvoetbal': 'Onbekend',
             'Western Games': 'Onbekend',
             'Casino avond': 'Onbekend',
             'Action Painting': 'Onbekend',
             'VR Game La Casa de Papel': 'Onbekend',
             'Wie is de Mol': 'Onbekend',
             'Highland Games': 'Onbekend'}},
 {'name': 'Jeremy',
  'week_mode': 'ONEVEN',
  'notes': 'Do hele dag; vr tot 17:00; weekend niet',
  'driving_license': 'Ja',
  'own_transport': 'Onbekend',
  'active': True,
  'availability': {'Ma -17': 'niet',
                   'Ma >17': 'niet',
                   'Di -17': 'niet',
                   'Di >17': 'niet',
                   'Wo -17': 'niet',
                   'Wo >17': 'niet',
                   'Do -17': 'beschikbaar',
                   'Do >17': 'beschikbaar',
                   'Vr -17': 'beschikbaar',
                   'Vr >17': 'niet',
                   'Za -17': 'niet',
                   'Za >17': 'niet',
                   'Zo -17': 'niet',
                   'Zo >17': 'niet'},
  'skills': {'Ik hou van Holland': 'Onbekend',
             'De Alleskunner': 'Onbekend',
             'Minute to Win It': 'Onbekend',
             'Moordspel': 'Ja',
             'Crazy Bingo': 'Onbekend',
             'Boogschieten': 'Onbekend',
             'Pubquiz': 'Onbekend',
             'Alles mag vandaag': 'Onbekend',
             'Hunted': 'Onbekend',
             'Expeditie Robinson': 'Onbekend',
             'Archery Tag': 'Onbekend',
             'Bubbelvoetbal': 'Onbekend',
             'Western Games': 'Onbekend',
             'Casino avond': 'Onbekend',
             'Action Painting': 'Onbekend',
             'VR Game La Casa de Papel': 'Onbekend',
             'Wie is de Mol': 'Onbekend',
             'Highland Games': 'Onbekend'}},
 {'name': 'Jeremy',
  'week_mode': 'EVEN',
  'notes': 'Do t/m zo beschikbaar',
  'driving_license': 'Ja',
  'own_transport': 'Onbekend',
  'active': True,
  'availability': {'Ma -17': 'niet',
                   'Ma >17': 'niet',
                   'Di -17': 'niet',
                   'Di >17': 'niet',
                   'Wo -17': 'niet',
                   'Wo >17': 'niet',
                   'Do -17': 'beschikbaar',
                   'Do >17': 'beschikbaar',
                   'Vr -17': 'beschikbaar',
                   'Vr >17': 'beschikbaar',
                   'Za -17': 'beschikbaar',
                   'Za >17': 'beschikbaar',
                   'Zo -17': 'beschikbaar',
                   'Zo >17': 'beschikbaar'},
  'skills': {'Ik hou van Holland': 'Onbekend',
             'De Alleskunner': 'Onbekend',
             'Minute to Win It': 'Onbekend',
             'Moordspel': 'Ja',
             'Crazy Bingo': 'Onbekend',
             'Boogschieten': 'Onbekend',
             'Pubquiz': 'Onbekend',
             'Alles mag vandaag': 'Onbekend',
             'Hunted': 'Onbekend',
             'Expeditie Robinson': 'Onbekend',
             'Archery Tag': 'Onbekend',
             'Bubbelvoetbal': 'Onbekend',
             'Western Games': 'Onbekend',
             'Casino avond': 'Onbekend',
             'Action Painting': 'Onbekend',
             'VR Game La Casa de Papel': 'Onbekend',
             'Wie is de Mol': 'Onbekend',
             'Highland Games': 'Onbekend'}},
 {'name': 'Tim Kuipers',
  'week_mode': '',
  'notes': 'Donderdag, vrijdag en zondag',
  'driving_license': 'Ja',
  'own_transport': 'Onbekend',
  'active': True,
  'availability': {'Ma -17': 'niet',
                   'Ma >17': 'niet',
                   'Di -17': 'niet',
                   'Di >17': 'niet',
                   'Wo -17': 'niet',
                   'Wo >17': 'niet',
                   'Do -17': 'beschikbaar',
                   'Do >17': 'beschikbaar',
                   'Vr -17': 'beschikbaar',
                   'Vr >17': 'beschikbaar',
                   'Za -17': 'niet',
                   'Za >17': 'niet',
                   'Zo -17': 'beschikbaar',
                   'Zo >17': 'beschikbaar'},
  'skills': {'Ik hou van Holland': 'Onbekend',
             'De Alleskunner': 'Onbekend',
             'Minute to Win It': 'Onbekend',
             'Moordspel': 'Ja',
             'Crazy Bingo': 'Onbekend',
             'Boogschieten': 'Onbekend',
             'Pubquiz': 'Onbekend',
             'Alles mag vandaag': 'Onbekend',
             'Hunted': 'Onbekend',
             'Expeditie Robinson': 'Onbekend',
             'Archery Tag': 'Onbekend',
             'Bubbelvoetbal': 'Onbekend',
             'Western Games': 'Onbekend',
             'Casino avond': 'Onbekend',
             'Action Painting': 'Onbekend',
             'VR Game La Casa de Papel': 'Onbekend',
             'Wie is de Mol': 'Onbekend',
             'Highland Games': 'Onbekend'}},
 {'name': 'Floor',
  'week_mode': '',
  'notes': 'Beschikbaarheid nog afspreken',
  'driving_license': 'Ja',
  'own_transport': 'Onbekend',
  'active': True,
  'availability': {'Ma -17': 'onbekend',
                   'Ma >17': 'onbekend',
                   'Di -17': 'onbekend',
                   'Di >17': 'onbekend',
                   'Wo -17': 'onbekend',
                   'Wo >17': 'onbekend',
                   'Do -17': 'onbekend',
                   'Do >17': 'onbekend',
                   'Vr -17': 'onbekend',
                   'Vr >17': 'onbekend',
                   'Za -17': 'onbekend',
                   'Za >17': 'onbekend',
                   'Zo -17': 'onbekend',
                   'Zo >17': 'onbekend'},
  'skills': {'Ik hou van Holland': 'Onbekend',
             'De Alleskunner': 'Onbekend',
             'Minute to Win It': 'Onbekend',
             'Moordspel': 'Ja',
             'Crazy Bingo': 'Onbekend',
             'Boogschieten': 'Onbekend',
             'Pubquiz': 'Onbekend',
             'Alles mag vandaag': 'Onbekend',
             'Hunted': 'Onbekend',
             'Expeditie Robinson': 'Onbekend',
             'Archery Tag': 'Onbekend',
             'Bubbelvoetbal': 'Onbekend',
             'Western Games': 'Onbekend',
             'Casino avond': 'Onbekend',
             'Action Painting': 'Onbekend',
             'VR Game La Casa de Papel': 'Onbekend',
             'Wie is de Mol': 'Onbekend',
             'Highland Games': 'Onbekend'}},
 {'name': 'Jelte',
  'week_mode': '',
  'notes': 'Beschikbaarheid nog afspreken',
  'driving_license': 'Ja',
  'own_transport': 'Onbekend',
  'active': True,
  'availability': {'Ma -17': 'onbekend',
                   'Ma >17': 'onbekend',
                   'Di -17': 'onbekend',
                   'Di >17': 'onbekend',
                   'Wo -17': 'onbekend',
                   'Wo >17': 'onbekend',
                   'Do -17': 'onbekend',
                   'Do >17': 'onbekend',
                   'Vr -17': 'onbekend',
                   'Vr >17': 'onbekend',
                   'Za -17': 'onbekend',
                   'Za >17': 'onbekend',
                   'Zo -17': 'onbekend',
                   'Zo >17': 'onbekend'},
  'skills': {'Ik hou van Holland': 'Onbekend',
             'De Alleskunner': 'Onbekend',
             'Minute to Win It': 'Onbekend',
             'Moordspel': 'Ja',
             'Crazy Bingo': 'Onbekend',
             'Boogschieten': 'Onbekend',
             'Pubquiz': 'Onbekend',
             'Alles mag vandaag': 'Onbekend',
             'Hunted': 'Onbekend',
             'Expeditie Robinson': 'Onbekend',
             'Archery Tag': 'Onbekend',
             'Bubbelvoetbal': 'Onbekend',
             'Western Games': 'Onbekend',
             'Casino avond': 'Onbekend',
             'Action Painting': 'Onbekend',
             'VR Game La Casa de Papel': 'Onbekend',
             'Wie is de Mol': 'Onbekend',
             'Highland Games': 'Onbekend'}}]
