services:
  - type: web
    name: jp-planner
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: ORS_API_KEY
        sync: false
